# Generated by Django 2.2.4 on 2019-11-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empoyee',
            fields=[
                ('Emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Emp_name', models.CharField(max_length=30)),
                ('Emp_loginname', models.CharField(max_length=30, unique=True)),
                ('Emp_password', models.CharField(max_length=30)),
                ('Emp_doj', models.DateField()),
                ('Emp_contact', models.IntegerField()),
                ('Emp_email', models.EmailField(max_length=254, unique=True)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
    ]
