# Generated by Django 2.2.4 on 2019-11-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HDMS_ADMIN', '0002_auto_20191119_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceDepartment',
            fields=[
                ('Fd_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Fd_name', models.CharField(max_length=30)),
                ('Fd_loginname', models.CharField(max_length=30, unique=True)),
                ('Fd_password', models.CharField(max_length=30)),
                ('Fd_doj', models.DateField()),
                ('Fd_contact', models.IntegerField(unique=True)),
                ('Fd_email', models.EmailField(max_length=254, unique=True)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
    ]
