# Generated by Django 2.2.4 on 2019-11-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HDMS_ADMIN', '0003_financedepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('Device_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Device_name', models.CharField(max_length=30)),
                ('Date_Of_Purchase', models.DateField()),
                ('Cost_Of_Devices', models.FloatField()),
                ('Total_Devices', models.IntegerField()),
            ],
        ),
    ]
