# Generated by Django 2.2.4 on 2019-11-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HDMS_ADMIN', '0004_devices'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRequest',
            fields=[
                ('DR_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('DEVICE_ID', models.IntegerField()),
                ('DOCTOR_ID', models.IntegerField()),
                ('STATUS_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDevices',
            fields=[
                ('DD_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('DEVICE_ID', models.IntegerField()),
                ('DOCTOR_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('STATUS_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('STATUS', models.CharField(max_length=30)),
            ],
        ),
    ]
