# Generated by Django 2.2.4 on 2019-11-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HDMS_ADMIN', '0005_devicerequest_doctordevices_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicerequest',
            name='DEVICE_NAME',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='devicerequest',
            name='DOCTOR_NAME',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
