# Generated by Django 2.2.4 on 2019-11-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HDMS_LOGIN', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocterRegistration',
            fields=[
                ('Doctor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Doctor_name', models.CharField(max_length=30)),
                ('Login_name', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30, unique=True)),
                ('Designation', models.CharField(max_length=30)),
                ('Date_of_joining', models.DateField()),
                ('Contact', models.IntegerField(unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
