# Generated by Django 2.2.4 on 2019-11-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HDMS_LOGIN', '0002_docterregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='docterregistration',
            name='type',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
